using Marklio.Stdf;
using Marklio.Stdf.Records;
using Xunit;
using Xunit.Abstractions;

namespace Marklio.Stdf.Tests;

/// <summary>
/// Integration tests using synthetic STDF data generated by our own writer.
/// Covers reading, record structure validation, interface pattern matching,
/// sync/async parity, and byte-exact round-tripping.
/// </summary>
public class IntegrationTests(ITestOutputHelper output)
{
    [Theory]
    [InlineData(nameof(SyntheticStdf.SmallLe))]
    [InlineData(nameof(SyntheticStdf.MediumLe))]
    [InlineData(nameof(SyntheticStdf.MediumBe))]
    [InlineData(nameof(SyntheticStdf.FullMir))]
    public async Task RoundTrip_ByteExact(string datasetName)
    {
        var originalBytes = GetDataset(datasetName);

        // Read all records
        var records = new List<StdfRecord>();
        using var ms = new MemoryStream(originalBytes);
        await foreach (var rec in StdfFile.ReadAsync(ms))
        {
            records.Add(rec);
        }

        // Detect endianness from FAR for writing
        var endianness = Endianness.LittleEndian;
        if (records[0] is Far farRec)
            endianness = farRec.CpuType == 1 ? Endianness.BigEndian : Endianness.LittleEndian;

        output.WriteLine($"Read {records.Count} records from {originalBytes.Length} bytes (endianness: {endianness})");

        // Write them all back with correct endianness
        var writerOptions = new StdfWriterOptions { Endianness = endianness };
        using var outputStream = new MemoryStream();
        await using (var writer = StdfFile.OpenWrite(outputStream, writerOptions))
        {
            foreach (var rec in records)
            {
                await writer.WriteAsync(rec);
            }
        }

        var roundTrippedBytes = outputStream.ToArray();
        output.WriteLine($"Wrote {roundTrippedBytes.Length} bytes");

        Assert.Equal(originalBytes.Length, roundTrippedBytes.Length);

        // Byte-exact comparison
        for (int i = 0; i < originalBytes.Length; i++)
        {
            if (originalBytes[i] != roundTrippedBytes[i])
            {
                var start = Math.Max(0, i - 8);
                var end = Math.Min(originalBytes.Length, i + 8);
                output.WriteLine($"First byte mismatch at offset {i}: expected 0x{originalBytes[i]:X2}, got 0x{roundTrippedBytes[i]:X2}");
                output.WriteLine($"Original:     {BitConverter.ToString(originalBytes[start..end])}");
                output.WriteLine($"RoundTripped: {BitConverter.ToString(roundTrippedBytes[start..end])}");
                Assert.Fail($"Byte mismatch at offset {i}");
                return;
            }
        }

        output.WriteLine("PASS: Byte-exact round-trip verified!");
    }

    [Fact]
    public async Task MediumLe_HasExpectedRecordStructure()
    {
        var records = StdfFile.Read(SyntheticStdf.MediumLe.Value).ToList();

        var far = Assert.IsType<Far>(records[0]);
        Assert.Equal((byte)2, far.CpuType);
        Assert.Equal((byte)4, far.StdfVersion);

        Assert.Contains(records, r => r is Mir);
        Assert.Contains(records, r => r is Mrr);
        Assert.Contains(records, r => r is Wir);
        Assert.Contains(records, r => r is Wcr);
        Assert.Contains(records, r => r is Hbr);
        Assert.Contains(records, r => r is Sbr);
        Assert.Contains(records, r => r is Pcr);
        Assert.Contains(records, r => r is Tsr);
        Assert.Contains(records, r => r is Wrr);
        Assert.Contains(records, r => r is Bps);
        Assert.Contains(records, r => r is Eps);
        Assert.Contains(records, r => r is Dtr);
        Assert.Contains(records, r => r is Pmr);
        Assert.Contains(records, r => r is Sdr);

        // Should have balanced PIR/PRR
        var pirCount = records.Count(r => r is Pir);
        var prrCount = records.Count(r => r is Prr);
        output.WriteLine($"PIR: {pirCount}, PRR: {prrCount}");
        Assert.Equal(pirCount, prrCount);
        Assert.Equal(50, pirCount);
    }

    [Fact]
    public async Task MediumBe_DetectsEndianness()
    {
        var records = StdfFile.Read(SyntheticStdf.MediumBe.Value).ToList();
        var far = Assert.IsType<Far>(records[0]);
        Assert.Equal((byte)1, far.CpuType); // big-endian
    }

    [Fact]
    public async Task InterfacePatternMatching()
    {
        var headSiteRecords = 0;
        var testRecords = 0;
        var binRecords = 0;

        foreach (var rec in StdfFile.Read(SyntheticStdf.MediumLe.Value))
        {
            if (rec is IHeadSiteRecord) headSiteRecords++;
            if (rec is ITestRecord) testRecords++;
            if (rec is IBinRecord) binRecords++;
        }

        output.WriteLine($"IHeadSiteRecord: {headSiteRecords}");
        output.WriteLine($"ITestRecord: {testRecords}");
        output.WriteLine($"IBinRecord: {binRecords}");

        Assert.True(testRecords > 0, "Should have test records (PTR/FTR)");
        Assert.True(binRecords > 0, "Should have bin records (HBR/SBR)");
    }

    [Fact]
    public void NoUnknownRecords()
    {
        foreach (var rec in StdfFile.Read(SyntheticStdf.MediumLe.Value))
        {
            Assert.False(rec is UnknownRecord,
                $"Unexpected unknown record: type={rec.RecordType}, sub={rec.RecordSubType}");
        }
    }

    [Fact]
    public async Task SyncAndAsyncMatch()
    {
        var data = SyntheticStdf.MediumLe.Value;
        var syncRecords = StdfFile.Read(data).ToList();

        using var ms = new MemoryStream(data);
        var asyncRecords = new List<StdfRecord>();
        await foreach (var rec in StdfFile.ReadAsync(ms))
            asyncRecords.Add(rec);

        Assert.Equal(asyncRecords.Count, syncRecords.Count);
        for (int i = 0; i < asyncRecords.Count; i++)
        {
            Assert.Equal(asyncRecords[i].RecordType, syncRecords[i].RecordType);
            Assert.Equal(asyncRecords[i].RecordSubType, syncRecords[i].RecordSubType);
        }
    }

    [Fact]
    public void FullMir_AllFieldsPresent()
    {
        var records = StdfFile.Read(SyntheticStdf.FullMir.Value).ToList();
        var mir = Assert.IsType<Mir>(records[1]);

        // Verify that even the last fields (>32 bit positions) survived round-trip
        Assert.Equal("SUPER-A", mir.SupervisorName);
        Assert.Equal("SN-12345", mir.SerialNumber);
        Assert.Equal("ROM-42", mir.RomCode);
        Assert.Equal("ENG-001", mir.EngineeringId);
        Assert.Equal("REV-C", mir.DesignRevision);
        Assert.Equal("SPEC-001", mir.SpecificationName);
        Assert.Equal("1.0", mir.SpecificationVersion);
        Assert.Equal("FULL-MIR-LOT", mir.LotId);

        output.WriteLine($"MIR round-tripped with all 38 fields including >32-bit positions");
    }

    private static byte[] GetDataset(string name) => name switch
    {
        nameof(SyntheticStdf.SmallLe) => SyntheticStdf.SmallLe.Value,
        nameof(SyntheticStdf.MediumLe) => SyntheticStdf.MediumLe.Value,
        nameof(SyntheticStdf.MediumBe) => SyntheticStdf.MediumBe.Value,
        nameof(SyntheticStdf.FullMir) => SyntheticStdf.FullMir.Value,
        _ => throw new ArgumentException($"Unknown dataset: {name}"),
    };
}
