using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Marklio.Stdf.Generator;

/// <summary>
/// Emits the generated C# source for STDF record partials and the registry.
/// </summary>
internal static class RecordEmitter
{
    public static string EmitRecordPartial(RecordMetadata record)
    {
        var sb = new StringBuilder();
        var fields = record.Fields.OrderBy(f => f.DeclarationOrder).ToList();
        var wireCountFields = fields.Where(f => f.IsWireCount).ToList();
        var countedArrayFields = fields.Where(f => f.CountedArrayGroup != null).ToList();

        var groupFirstArray = new Dictionary<string, string>();
        foreach (var f in countedArrayFields)
        {
            if (f.CountedArrayGroup != null && !groupFirstArray.ContainsKey(f.CountedArrayGroup))
                groupFirstArray[f.CountedArrayGroup] = f.PropertyName;
        }

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0282 // partial struct field ordering");
        sb.AppendLine();
        sb.AppendLine("using static Marklio.Stdf.IO.StdfSerializationHelpers;");
        sb.AppendLine();
        sb.AppendLine($"namespace {record.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"partial record struct {record.TypeName} : Marklio.Stdf.IStdfRecord");
        sb.AppendLine("{");

        int totalFields = fields.Count;
        int serializableFields = fields.Count(f => !f.IsWireCount);
        string presenceType = totalFields > 32 ? "ulong" : "uint";
        string literalSuffix = totalFields > 32 ? "UL" : "u";
        // Compute all-ones mask for ALL field positions (including wire counts)
        string allPresent = totalFields > 32
            ? $"0x{AllBitsMask(totalFields):X16}UL"
            : $"0x{(uint)AllBitsMask(totalFields):X8}u";
        sb.AppendLine($"    internal {presenceType} _fieldPresence;");
        sb.AppendLine();
        // Parameterless constructor: sets all presence bits so user-created records serialize fully
        sb.AppendLine($"    /// <summary>Initializes a new instance of the <see cref=\"{record.TypeName}\"/> record.</summary>");
        sb.AppendLine($"    public {record.TypeName}()");
        sb.AppendLine("    {");
        sb.AppendLine($"        _fieldPresence = {allPresent};");
        // Initialize non-nullable string properties to avoid CS8618
        foreach (var f in fields.Where(f => !f.IsWireCount && !f.IsNullable && f.StdfType == StdfFieldType.Cn))
            sb.AppendLine($"        {f.PropertyName} = string.Empty;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    static byte Marklio.Stdf.IStdfRecord.RecordType => {record.RecordType};");
        sb.AppendLine($"    static byte Marklio.Stdf.IStdfRecord.RecordSubType => {record.RecordSubType};");
        sb.AppendLine();

        // Deserialize
        EmitDeserialize(sb, record, fields);
        sb.AppendLine();

        // Serialize
        EmitSerialize(sb, record, fields, wireCountFields, groupFirstArray);
        sb.AppendLine();

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitDeserialize(StringBuilder sb, RecordMetadata record, List<FieldMetadata> fields)
    {
        sb.AppendLine($"    /// <summary>Deserializes a <see cref=\"{record.TypeName}\"/> from the specified reader.</summary>");
        sb.AppendLine($"    public static {record.TypeName} Deserialize(ref System.Buffers.SequenceReader<byte> reader, Marklio.Stdf.Endianness endianness)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var result = new {record.TypeName}();");
        sb.AppendLine("        result._fieldPresence = 0;");

        int bit = 0;
        int totalFields = fields.Count;
        foreach (var field in fields)
        {
            if (field.IsWireCount)
            {
                EmitWireCountRead(sb, field, bit, totalFields);
            }
            else if (field.CountedArrayGroup != null)
            {
                EmitCountedArrayRead(sb, field, bit, totalFields);
            }
            else
            {
                EmitScalarRead(sb, field, bit, totalFields);
            }
            bit++;
        }

        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
    }

    private static void EmitWireCountRead(StringBuilder sb, FieldMetadata field, int bit, int totalFields)
    {
        string local = $"_cnt_{field.WireCountGroup}";
        string suffix = totalFields > 32 ? "UL" : "u";
        string readExpr = field.StdfType switch
        {
            StdfFieldType.WireCountU1 => $"reader.TryRead(out byte _tmpByte_{field.WireCountGroup}) ? (ushort)_tmpByte_{field.WireCountGroup} : (ushort)0",
            StdfFieldType.WireCountU2 => "ReadU2(ref reader, endianness)",
            StdfFieldType.WireCountU4 => "(ushort)ReadU4(ref reader, endianness)",
            _ => "ReadU2(ref reader, endianness)",
        };

        sb.AppendLine($"        ushort {local} = {readExpr};");
        sb.AppendLine($"        result._fieldPresence |= (1{suffix} << {bit});");
    }

    private static void EmitCountedArrayRead(StringBuilder sb, FieldMetadata field, int bit, int totalFields)
    {
        string countLocal = $"_cnt_{field.CountedArrayGroup}";
        string propName = field.PropertyName;
        string suffix = totalFields > 32 ? "UL" : "u";

        string readExpr = field.StdfType switch
        {
            StdfFieldType.ArrayU1 => $"ReadU1Array(ref reader, {countLocal})",
            StdfFieldType.ArrayU2 => $"ReadU2Array(ref reader, {countLocal}, endianness)",
            StdfFieldType.ArrayU4 => $"ReadU4Array(ref reader, {countLocal}, endianness)",
            StdfFieldType.ArrayU8 => $"ReadU8Array(ref reader, {countLocal}, endianness)",
            StdfFieldType.ArrayI1 => $"ReadI1Array(ref reader, {countLocal})",
            StdfFieldType.ArrayI2 => $"ReadI2Array(ref reader, {countLocal}, endianness)",
            StdfFieldType.ArrayI4 => $"ReadI4Array(ref reader, {countLocal}, endianness)",
            StdfFieldType.ArrayI8 => $"ReadI8Array(ref reader, {countLocal}, endianness)",
            StdfFieldType.ArrayR4 => $"ReadR4Array(ref reader, {countLocal}, endianness)",
            StdfFieldType.ArrayR8 => $"ReadR8Array(ref reader, {countLocal}, endianness)",
            StdfFieldType.ArrayCn => $"ReadCnArray(ref reader, {countLocal})",
            StdfFieldType.ArraySn => $"ReadSnArray(ref reader, {countLocal}, endianness)",
            StdfFieldType.ArrayN1 => $"ReadNibbleArray(ref reader, {countLocal})",
            _ => $"ReadU1Array(ref reader, {countLocal})",
        };

        sb.AppendLine($"        if ({countLocal} > 0 && reader.Remaining > 0)");
        sb.AppendLine("        {");
        sb.AppendLine($"            result.{propName} = {readExpr};");
        sb.AppendLine("        }");
        // Always mark the array as present if its wire count was read,
        // even when count=0. This ensures serialization continues past
        // empty arrays to subsequent trailing-optional fields.
        sb.AppendLine($"        result._fieldPresence |= (1{suffix} << {bit});");
    }

    private static void EmitScalarRead(StringBuilder sb, FieldMetadata field, int bit, int totalFields)
    {
        string prop = field.PropertyName;
        string suffix = totalFields > 32 ? "UL" : "u";
        switch (field.StdfType)
        {
            case StdfFieldType.U1:
            case StdfFieldType.B1:
                sb.AppendLine($"        if (reader.TryRead(out byte _v{bit})) {{ result.{prop} = _v{bit}; result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.I1:
                sb.AppendLine($"        if (reader.TryRead(out byte _ub{bit})) {{ result.{prop} = (sbyte)_ub{bit}; result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.U2:
                sb.AppendLine($"        if (reader.Remaining >= 2) {{ result.{prop} = ReadU2(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.I2:
                sb.AppendLine($"        if (reader.Remaining >= 2) {{ result.{prop} = ReadI2(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.U4:
                sb.AppendLine($"        if (reader.Remaining >= 4) {{ result.{prop} = ReadU4(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.I4:
                sb.AppendLine($"        if (reader.Remaining >= 4) {{ result.{prop} = ReadI4(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.U8:
                sb.AppendLine($"        if (reader.Remaining >= 8) {{ result.{prop} = ReadU8(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.I8:
                sb.AppendLine($"        if (reader.Remaining >= 8) {{ result.{prop} = ReadI8(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.R4:
                sb.AppendLine($"        if (reader.Remaining >= 4) {{ result.{prop} = ReadR4(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.R8:
                sb.AppendLine($"        if (reader.Remaining >= 8) {{ result.{prop} = ReadR8(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.C1:
                sb.AppendLine($"        if (reader.TryRead(out byte _c{bit})) {{ result.{prop} = (char)_c{bit}; result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.Cn:
                sb.AppendLine($"        if (reader.Remaining >= 1) {{ result.{prop} = ReadCn(ref reader); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.Sn:
                sb.AppendLine($"        if (reader.Remaining >= 2) {{ result.{prop} = ReadSn(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.Cf:
                sb.AppendLine($"        if (reader.Remaining >= {field.FixedStringLength}) {{ result.{prop} = ReadCf(ref reader, {field.FixedStringLength}); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.Bn:
                sb.AppendLine($"        if (reader.Remaining >= 1) {{ result.{prop} = ReadBn(ref reader); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.Dn:
                sb.AppendLine($"        if (reader.Remaining >= 2) {{ result.{prop} = ReadDn(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.N1:
                sb.AppendLine($"        if (reader.TryRead(out byte _n{bit})) {{ result.{prop} = (byte)(_n{bit} & 0x0F); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.DateTime:
                sb.AppendLine($"        if (reader.Remaining >= 4) {{ result.{prop} = ReadDateTime(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
        }
    }

    private static void EmitSerialize(StringBuilder sb, RecordMetadata record, List<FieldMetadata> fields, List<FieldMetadata> wireCountFields, Dictionary<string, string> groupFirstArray)
    {
        sb.AppendLine($"    /// <summary>Serializes this <see cref=\"{record.TypeName}\"/> to the specified writer.</summary>");
        sb.AppendLine("    public void Serialize(System.Buffers.IBufferWriter<byte> writer, Marklio.Stdf.Endianness endianness)");
        sb.AppendLine("    {");

        foreach (var wc in wireCountFields)
        {
            if (wc.WireCountGroup != null && groupFirstArray.TryGetValue(wc.WireCountGroup, out var arrayProp))
            {
                int maxCount = wc.StdfType == StdfFieldType.WireCountU1 ? 255 : 65535;
                sb.AppendLine($"        int _rawCount_{wc.WireCountGroup} = {arrayProp}?.Length ?? 0;");
                if (wc.StdfType != StdfFieldType.WireCountU4)
                {
                    sb.AppendLine($"        if (_rawCount_{wc.WireCountGroup} > {maxCount})");
                    sb.AppendLine($"            throw new System.InvalidOperationException($\"Array length {{_rawCount_{wc.WireCountGroup}}} exceeds maximum count of {maxCount} for wire count group '{wc.WireCountGroup}'.\");");
                }
                sb.AppendLine($"        ushort _wireCount_{wc.WireCountGroup} = (ushort)_rawCount_{wc.WireCountGroup};");
            }
        }

        string suffix = fields.Count > 32 ? "UL" : "u";
        int bit = 0;
        foreach (var field in fields)
        {
            // Build the presence condition — for nullable fields, also check the value
            string presenceCheck = $"(_fieldPresence & (1{suffix} << {bit})) != 0";
            if (field.IsNullable && !field.IsWireCount && field.CountedArrayGroup == null)
            {
                if (IsValueTypeStdfField(field.StdfType))
                    presenceCheck += $" && {field.PropertyName}.HasValue";
                else
                    presenceCheck += $" && {field.PropertyName} != null";
            }

            sb.AppendLine($"        if ({presenceCheck})");
            sb.AppendLine("        {");

            if (field.IsWireCount)
            {
                string writeCall = field.StdfType switch
                {
                    StdfFieldType.WireCountU1 => $"WriteU1(writer, (byte)_wireCount_{field.WireCountGroup});",
                    StdfFieldType.WireCountU2 => $"WriteU2(writer, _wireCount_{field.WireCountGroup}, endianness);",
                    StdfFieldType.WireCountU4 => $"WriteU4(writer, (uint)_wireCount_{field.WireCountGroup}, endianness);",
                    _ => $"WriteU2(writer, _wireCount_{field.WireCountGroup}, endianness);",
                };
                sb.AppendLine($"            {writeCall}");
            }
            else if (field.CountedArrayGroup != null)
            {
                string propName = field.PropertyName;
                string writeCall = field.StdfType switch
                {
                    StdfFieldType.ArrayU1 => $"WriteU1Array(writer, {propName});",
                    StdfFieldType.ArrayU2 => $"WriteU2Array(writer, {propName}, endianness);",
                    StdfFieldType.ArrayU4 => $"WriteU4Array(writer, {propName}, endianness);",
                    StdfFieldType.ArrayU8 => $"WriteU8Array(writer, {propName}, endianness);",
                    StdfFieldType.ArrayI1 => $"WriteI1Array(writer, {propName});",
                    StdfFieldType.ArrayI2 => $"WriteI2Array(writer, {propName}, endianness);",
                    StdfFieldType.ArrayI4 => $"WriteI4Array(writer, {propName}, endianness);",
                    StdfFieldType.ArrayI8 => $"WriteI8Array(writer, {propName}, endianness);",
                    StdfFieldType.ArrayR4 => $"WriteR4Array(writer, {propName}, endianness);",
                    StdfFieldType.ArrayR8 => $"WriteR8Array(writer, {propName}, endianness);",
                    StdfFieldType.ArrayCn => $"WriteCnArray(writer, {propName});",
                    StdfFieldType.ArraySn => $"WriteSnArray(writer, {propName}, endianness);",
                    StdfFieldType.ArrayN1 => $"WriteNibbleArray(writer, {propName});",
                    _ => $"WriteU1Array(writer, {propName});",
                };
                sb.AppendLine($"            if ({propName} != null) {writeCall}");
            }
            else
            {
                string propName = field.PropertyName;
                // Reference types (string, byte[], BitArray) don't use .Value even when nullable
                bool isNullableValueType = field.IsNullable && IsValueTypeStdfField(field.StdfType);
                string val = isNullableValueType ? $"{propName}!.Value" : propName;
                string writeCall = field.StdfType switch
                {
                    StdfFieldType.U1 or StdfFieldType.B1 => $"WriteU1(writer, {val});",
                    StdfFieldType.I1 => $"WriteI1(writer, {val});",
                    StdfFieldType.U2 => $"WriteU2(writer, {val}, endianness);",
                    StdfFieldType.I2 => $"WriteI2(writer, {val}, endianness);",
                    StdfFieldType.U4 => $"WriteU4(writer, {val}, endianness);",
                    StdfFieldType.I4 => $"WriteI4(writer, {val}, endianness);",
                    StdfFieldType.U8 => $"WriteU8(writer, {val}, endianness);",
                    StdfFieldType.I8 => $"WriteI8(writer, {val}, endianness);",
                    StdfFieldType.R4 => $"WriteR4(writer, {val}, endianness);",
                    StdfFieldType.R8 => $"WriteR8(writer, {val}, endianness);",
                    StdfFieldType.C1 => $"WriteC1(writer, {val});",
                    StdfFieldType.Cn => $"WriteCn(writer, {val});",
                    StdfFieldType.Sn => $"WriteSn(writer, {val}, endianness);",
                    StdfFieldType.Cf => $"WriteCf(writer, {val}, {field.FixedStringLength});",
                    StdfFieldType.Bn => $"WriteBn(writer, {val});",
                    StdfFieldType.Dn => $"WriteDn(writer, {val}, endianness);",
                    StdfFieldType.N1 => $"WriteN1(writer, {val});",
                    StdfFieldType.DateTime => $"WriteDateTime(writer, {val}, endianness);",
                    _ => $"WriteU1(writer, {val});",
                };
                sb.AppendLine($"            {writeCall}");
            }

            sb.AppendLine("        }");
            sb.AppendLine("        else return;");
            bit++;
        }

        sb.AppendLine("    }");
    }

    public static string EmitRegistry(ImmutableArray<RecordMetadata> records)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Marklio.Stdf.IO;");
        sb.AppendLine();
        sb.AppendLine("internal static class RecordRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    internal static Marklio.Stdf.StdfRecord? Deserialize(byte recType, byte recSub, ref System.Buffers.SequenceReader<byte> reader, Marklio.Stdf.Endianness endianness)");
        sb.AppendLine("    {");
        sb.AppendLine("        return (recType, recSub) switch");
        sb.AppendLine("        {");

        foreach (var r in records)
            sb.AppendLine($"            ({r.RecordType}, {r.RecordSubType}) => new Marklio.Stdf.StdfRecord({r.Namespace}.{r.TypeName}.Deserialize(ref reader, endianness), {r.RecordType}, {r.RecordSubType}),");

        // Hand-rolled records that implement IStdfRecord directly (no [StdfRecord] attribute)
        sb.AppendLine("            (50, 10) => new Marklio.Stdf.StdfRecord(Marklio.Stdf.Records.Gdr.Deserialize(ref reader, endianness), 50, 10),");
        sb.AppendLine("            (15, 30) => new Marklio.Stdf.StdfRecord(Marklio.Stdf.Records.Str.Deserialize(ref reader, endianness), 15, 30),");

        sb.AppendLine("            _ => null,");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    internal static bool IsKnown(byte recType, byte recSub)");
        sb.AppendLine("    {");
        sb.AppendLine("        return (recType, recSub) switch");
        sb.AppendLine("        {");

        foreach (var r in records)
            sb.AppendLine($"            ({r.RecordType}, {r.RecordSubType}) => true,");

        sb.AppendLine("            (50, 10) => true,");
        sb.AppendLine("            (15, 30) => true,");
        sb.AppendLine("            _ => false,");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }



    private static ulong AllBitsMask(int bitCount)
    {
        if (bitCount >= 64) return ulong.MaxValue;
        if (bitCount <= 0) return 0;
        return (1UL << bitCount) - 1;
    }

    private static bool IsValueTypeStdfField(StdfFieldType t) => t switch
    {
        StdfFieldType.U1 or StdfFieldType.I1 or StdfFieldType.U2 or StdfFieldType.I2 or
        StdfFieldType.U4 or StdfFieldType.I4 or StdfFieldType.U8 or StdfFieldType.I8 or
        StdfFieldType.R4 or StdfFieldType.R8 or
        StdfFieldType.B1 or StdfFieldType.C1 or StdfFieldType.N1 or StdfFieldType.DateTime => true,
        _ => false,
    };
}
