using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Marklio.Stdf.Generator;

/// <summary>
/// Emits the generated C# source for STDF record partials and the registry.
/// </summary>
internal static class RecordEmitter
{
    public static string EmitRecordPartial(RecordMetadata record)
    {
        var sb = new StringBuilder();
        var fields = record.Fields.OrderBy(f => f.DeclarationOrder).ToList();
        var wireCountFields = fields.Where(f => f.IsWireCount).ToList();
        var countedArrayFields = fields.Where(f => f.CountedArrayGroup != null).ToList();

        var groupFirstArray = new Dictionary<string, string>();
        foreach (var f in countedArrayFields)
        {
            if (f.CountedArrayGroup != null && !groupFirstArray.ContainsKey(f.CountedArrayGroup))
                groupFirstArray[f.CountedArrayGroup] = f.PropertyName;
        }

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0282 // partial struct field ordering");
        sb.AppendLine();
        sb.AppendLine($"namespace {record.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"partial record struct {record.TypeName} : Marklio.Stdf.IStdfRecord");
        sb.AppendLine("{");

        int totalFields = fields.Count;
        int serializableFields = fields.Count(f => !f.IsWireCount);
        string presenceType = totalFields > 32 ? "ulong" : "uint";
        string literalSuffix = totalFields > 32 ? "UL" : "u";
        // Compute all-ones mask for ALL field positions (including wire counts)
        string allPresent = totalFields > 32
            ? $"0x{AllBitsMask(totalFields):X16}UL"
            : $"0x{(uint)AllBitsMask(totalFields):X8}u";
        sb.AppendLine($"    internal {presenceType} _fieldPresence;");
        sb.AppendLine();
        // Parameterless constructor: sets all presence bits so user-created records serialize fully
        sb.AppendLine($"    /// <summary>Initializes a new instance of the <see cref=\"{record.TypeName}\"/> record.</summary>");
        sb.AppendLine($"    public {record.TypeName}()");
        sb.AppendLine("    {");
        sb.AppendLine($"        _fieldPresence = {allPresent};");
        // Initialize non-nullable string properties to avoid CS8618
        foreach (var f in fields.Where(f => !f.IsWireCount && !f.IsNullable && f.StdfType == StdfFieldType.Cn))
            sb.AppendLine($"        {f.PropertyName} = string.Empty;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    static byte Marklio.Stdf.IStdfRecord.RecordType => {record.RecordType};");
        sb.AppendLine($"    static byte Marklio.Stdf.IStdfRecord.RecordSubType => {record.RecordSubType};");
        sb.AppendLine();

        // Deserialize
        EmitDeserialize(sb, record, fields);
        sb.AppendLine();

        // Serialize
        EmitSerialize(sb, record, fields, wireCountFields, groupFirstArray);
        sb.AppendLine();

        // Helper methods
        sb.Append(HelperSource);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitDeserialize(StringBuilder sb, RecordMetadata record, List<FieldMetadata> fields)
    {
        sb.AppendLine($"    /// <summary>Deserializes a <see cref=\"{record.TypeName}\"/> from the specified reader.</summary>");
        sb.AppendLine($"    public static {record.TypeName} Deserialize(ref System.Buffers.SequenceReader<byte> reader, Marklio.Stdf.Endianness endianness)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var result = new {record.TypeName}();");
        sb.AppendLine("        result._fieldPresence = 0;");

        int bit = 0;
        int totalFields = fields.Count;
        foreach (var field in fields)
        {
            if (field.IsWireCount)
            {
                EmitWireCountRead(sb, field, bit, totalFields);
            }
            else if (field.CountedArrayGroup != null)
            {
                EmitCountedArrayRead(sb, field, bit, totalFields);
            }
            else
            {
                EmitScalarRead(sb, field, bit, totalFields);
            }
            bit++;
        }

        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
    }

    private static void EmitWireCountRead(StringBuilder sb, FieldMetadata field, int bit, int totalFields)
    {
        string local = $"_cnt_{field.WireCountGroup}";
        string suffix = totalFields > 32 ? "UL" : "u";
        string readExpr = field.StdfType switch
        {
            StdfFieldType.WireCountU1 => $"reader.TryRead(out byte _tmpByte_{field.WireCountGroup}) ? (ushort)_tmpByte_{field.WireCountGroup} : (ushort)0",
            StdfFieldType.WireCountU2 => "ReadU2(ref reader, endianness)",
            StdfFieldType.WireCountU4 => "(ushort)ReadU4(ref reader, endianness)",
            _ => "ReadU2(ref reader, endianness)",
        };

        sb.AppendLine($"        ushort {local} = {readExpr};");
        sb.AppendLine($"        result._fieldPresence |= (1{suffix} << {bit});");
    }

    private static void EmitCountedArrayRead(StringBuilder sb, FieldMetadata field, int bit, int totalFields)
    {
        string countLocal = $"_cnt_{field.CountedArrayGroup}";
        string propName = field.PropertyName;
        string suffix = totalFields > 32 ? "UL" : "u";

        string readExpr = field.StdfType switch
        {
            StdfFieldType.ArrayU1 => $"ReadU1Array(ref reader, {countLocal})",
            StdfFieldType.ArrayU2 => $"ReadU2Array(ref reader, {countLocal}, endianness)",
            StdfFieldType.ArrayU4 => $"ReadU4Array(ref reader, {countLocal}, endianness)",
            StdfFieldType.ArrayU8 => $"ReadU8Array(ref reader, {countLocal}, endianness)",
            StdfFieldType.ArrayI1 => $"ReadI1Array(ref reader, {countLocal})",
            StdfFieldType.ArrayI2 => $"ReadI2Array(ref reader, {countLocal}, endianness)",
            StdfFieldType.ArrayI4 => $"ReadI4Array(ref reader, {countLocal}, endianness)",
            StdfFieldType.ArrayI8 => $"ReadI8Array(ref reader, {countLocal}, endianness)",
            StdfFieldType.ArrayR4 => $"ReadR4Array(ref reader, {countLocal}, endianness)",
            StdfFieldType.ArrayR8 => $"ReadR8Array(ref reader, {countLocal}, endianness)",
            StdfFieldType.ArrayCn => $"ReadCnArray(ref reader, {countLocal})",
            StdfFieldType.ArraySn => $"ReadSnArray(ref reader, {countLocal}, endianness)",
            StdfFieldType.ArrayN1 => $"ReadNibbleArray(ref reader, {countLocal})",
            _ => $"ReadU1Array(ref reader, {countLocal})",
        };

        sb.AppendLine($"        if ({countLocal} > 0 && reader.Remaining > 0)");
        sb.AppendLine("        {");
        sb.AppendLine($"            result.{propName} = {readExpr};");
        sb.AppendLine("        }");
        // Always mark the array as present if its wire count was read,
        // even when count=0. This ensures serialization continues past
        // empty arrays to subsequent trailing-optional fields.
        sb.AppendLine($"        result._fieldPresence |= (1{suffix} << {bit});");
    }

    private static void EmitScalarRead(StringBuilder sb, FieldMetadata field, int bit, int totalFields)
    {
        string prop = field.PropertyName;
        string suffix = totalFields > 32 ? "UL" : "u";
        switch (field.StdfType)
        {
            case StdfFieldType.U1:
            case StdfFieldType.B1:
                sb.AppendLine($"        if (reader.TryRead(out byte _v{bit})) {{ result.{prop} = _v{bit}; result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.I1:
                sb.AppendLine($"        if (reader.TryRead(out byte _ub{bit})) {{ result.{prop} = (sbyte)_ub{bit}; result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.U2:
                sb.AppendLine($"        if (reader.Remaining >= 2) {{ result.{prop} = ReadU2(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.I2:
                sb.AppendLine($"        if (reader.Remaining >= 2) {{ result.{prop} = ReadI2(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.U4:
                sb.AppendLine($"        if (reader.Remaining >= 4) {{ result.{prop} = ReadU4(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.I4:
                sb.AppendLine($"        if (reader.Remaining >= 4) {{ result.{prop} = ReadI4(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.U8:
                sb.AppendLine($"        if (reader.Remaining >= 8) {{ result.{prop} = ReadU8(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.I8:
                sb.AppendLine($"        if (reader.Remaining >= 8) {{ result.{prop} = ReadI8(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.R4:
                sb.AppendLine($"        if (reader.Remaining >= 4) {{ result.{prop} = ReadR4(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.R8:
                sb.AppendLine($"        if (reader.Remaining >= 8) {{ result.{prop} = ReadR8(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.C1:
                sb.AppendLine($"        if (reader.TryRead(out byte _c{bit})) {{ result.{prop} = (char)_c{bit}; result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.Cn:
                sb.AppendLine($"        if (reader.Remaining >= 1) {{ result.{prop} = ReadCn(ref reader); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.Sn:
                sb.AppendLine($"        if (reader.Remaining >= 2) {{ result.{prop} = ReadSn(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.Cf:
                sb.AppendLine($"        if (reader.Remaining >= {field.FixedStringLength}) {{ result.{prop} = ReadCf(ref reader, {field.FixedStringLength}); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.Bn:
                sb.AppendLine($"        if (reader.Remaining >= 1) {{ result.{prop} = ReadBn(ref reader); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.Dn:
                sb.AppendLine($"        if (reader.Remaining >= 2) {{ result.{prop} = ReadDn(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.N1:
                sb.AppendLine($"        if (reader.TryRead(out byte _n{bit})) {{ result.{prop} = (byte)(_n{bit} & 0x0F); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
            case StdfFieldType.DateTime:
                sb.AppendLine($"        if (reader.Remaining >= 4) {{ result.{prop} = ReadDateTime(ref reader, endianness); result._fieldPresence |= (1{suffix} << {bit}); }}");
                sb.AppendLine("        else return result;");
                break;
        }
    }

    private static void EmitSerialize(StringBuilder sb, RecordMetadata record, List<FieldMetadata> fields, List<FieldMetadata> wireCountFields, Dictionary<string, string> groupFirstArray)
    {
        sb.AppendLine($"    /// <summary>Serializes this <see cref=\"{record.TypeName}\"/> to the specified writer.</summary>");
        sb.AppendLine("    public void Serialize(System.Buffers.IBufferWriter<byte> writer, Marklio.Stdf.Endianness endianness)");
        sb.AppendLine("    {");

        foreach (var wc in wireCountFields)
        {
            if (wc.WireCountGroup != null && groupFirstArray.TryGetValue(wc.WireCountGroup, out var arrayProp))
                sb.AppendLine($"        ushort _wireCount_{wc.WireCountGroup} = (ushort)({arrayProp}?.Length ?? 0);");
        }

        string suffix = fields.Count > 32 ? "UL" : "u";
        int bit = 0;
        foreach (var field in fields)
        {
            // Build the presence condition — for nullable fields, also check the value
            string presenceCheck = $"(_fieldPresence & (1{suffix} << {bit})) != 0";
            if (field.IsNullable && !field.IsWireCount && field.CountedArrayGroup == null)
            {
                if (IsValueTypeStdfField(field.StdfType))
                    presenceCheck += $" && {field.PropertyName}.HasValue";
                else
                    presenceCheck += $" && {field.PropertyName} != null";
            }

            sb.AppendLine($"        if ({presenceCheck})");
            sb.AppendLine("        {");

            if (field.IsWireCount)
            {
                string writeCall = field.StdfType switch
                {
                    StdfFieldType.WireCountU1 => $"WriteU1(writer, (byte)_wireCount_{field.WireCountGroup});",
                    StdfFieldType.WireCountU2 => $"WriteU2(writer, _wireCount_{field.WireCountGroup}, endianness);",
                    StdfFieldType.WireCountU4 => $"WriteU4(writer, (uint)_wireCount_{field.WireCountGroup}, endianness);",
                    _ => $"WriteU2(writer, _wireCount_{field.WireCountGroup}, endianness);",
                };
                sb.AppendLine($"            {writeCall}");
            }
            else if (field.CountedArrayGroup != null)
            {
                string propName = field.PropertyName;
                string writeCall = field.StdfType switch
                {
                    StdfFieldType.ArrayU1 => $"WriteU1Array(writer, {propName});",
                    StdfFieldType.ArrayU2 => $"WriteU2Array(writer, {propName}, endianness);",
                    StdfFieldType.ArrayU4 => $"WriteU4Array(writer, {propName}, endianness);",
                    StdfFieldType.ArrayU8 => $"WriteU8Array(writer, {propName}, endianness);",
                    StdfFieldType.ArrayI1 => $"WriteI1Array(writer, {propName});",
                    StdfFieldType.ArrayI2 => $"WriteI2Array(writer, {propName}, endianness);",
                    StdfFieldType.ArrayI4 => $"WriteI4Array(writer, {propName}, endianness);",
                    StdfFieldType.ArrayI8 => $"WriteI8Array(writer, {propName}, endianness);",
                    StdfFieldType.ArrayR4 => $"WriteR4Array(writer, {propName}, endianness);",
                    StdfFieldType.ArrayR8 => $"WriteR8Array(writer, {propName}, endianness);",
                    StdfFieldType.ArrayCn => $"WriteCnArray(writer, {propName});",
                    StdfFieldType.ArraySn => $"WriteSnArray(writer, {propName}, endianness);",
                    StdfFieldType.ArrayN1 => $"WriteNibbleArray(writer, {propName});",
                    _ => $"WriteU1Array(writer, {propName});",
                };
                sb.AppendLine($"            if ({propName} != null) {writeCall}");
            }
            else
            {
                string propName = field.PropertyName;
                // Reference types (string, byte[], BitArray) don't use .Value even when nullable
                bool isNullableValueType = field.IsNullable && IsValueTypeStdfField(field.StdfType);
                string val = isNullableValueType ? $"{propName}!.Value" : propName;
                string writeCall = field.StdfType switch
                {
                    StdfFieldType.U1 or StdfFieldType.B1 => $"WriteU1(writer, {val});",
                    StdfFieldType.I1 => $"WriteI1(writer, {val});",
                    StdfFieldType.U2 => $"WriteU2(writer, {val}, endianness);",
                    StdfFieldType.I2 => $"WriteI2(writer, {val}, endianness);",
                    StdfFieldType.U4 => $"WriteU4(writer, {val}, endianness);",
                    StdfFieldType.I4 => $"WriteI4(writer, {val}, endianness);",
                    StdfFieldType.U8 => $"WriteU8(writer, {val}, endianness);",
                    StdfFieldType.I8 => $"WriteI8(writer, {val}, endianness);",
                    StdfFieldType.R4 => $"WriteR4(writer, {val}, endianness);",
                    StdfFieldType.R8 => $"WriteR8(writer, {val}, endianness);",
                    StdfFieldType.C1 => $"WriteC1(writer, {val});",
                    StdfFieldType.Cn => $"WriteCn(writer, {val});",
                    StdfFieldType.Sn => $"WriteSn(writer, {val}, endianness);",
                    StdfFieldType.Cf => $"WriteCf(writer, {val}, {field.FixedStringLength});",
                    StdfFieldType.Bn => $"WriteBn(writer, {val});",
                    StdfFieldType.Dn => $"WriteDn(writer, {val}, endianness);",
                    StdfFieldType.N1 => $"WriteN1(writer, {val});",
                    StdfFieldType.DateTime => $"WriteDateTime(writer, {val}, endianness);",
                    _ => $"WriteU1(writer, {val});",
                };
                sb.AppendLine($"            {writeCall}");
            }

            sb.AppendLine("        }");
            sb.AppendLine("        else return;");
            bit++;
        }

        sb.AppendLine("    }");
    }

    public static string EmitRegistry(ImmutableArray<RecordMetadata> records)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Marklio.Stdf.IO;");
        sb.AppendLine();
        sb.AppendLine("internal static class RecordRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    internal static Marklio.Stdf.StdfRecord? Deserialize(byte recType, byte recSub, ref System.Buffers.SequenceReader<byte> reader, Marklio.Stdf.Endianness endianness)");
        sb.AppendLine("    {");
        sb.AppendLine("        return (recType, recSub) switch");
        sb.AppendLine("        {");

        foreach (var r in records)
            sb.AppendLine($"            ({r.RecordType}, {r.RecordSubType}) => new Marklio.Stdf.StdfRecord({r.Namespace}.{r.TypeName}.Deserialize(ref reader, endianness), {r.RecordType}, {r.RecordSubType}),");

        // Hand-rolled records that implement IStdfRecord directly (no [StdfRecord] attribute)
        sb.AppendLine("            (50, 10) => new Marklio.Stdf.StdfRecord(Marklio.Stdf.Records.Gdr.Deserialize(ref reader, endianness), 50, 10),");
        sb.AppendLine("            (15, 30) => new Marklio.Stdf.StdfRecord(Marklio.Stdf.Records.Str.Deserialize(ref reader, endianness), 15, 30),");

        sb.AppendLine("            _ => null,");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    internal static bool IsKnown(byte recType, byte recSub)");
        sb.AppendLine("    {");
        sb.AppendLine("        return (recType, recSub) switch");
        sb.AppendLine("        {");

        foreach (var r in records)
            sb.AppendLine($"            ({r.RecordType}, {r.RecordSubType}) => true,");

        sb.AppendLine("            (50, 10) => true,");
        sb.AppendLine("            (15, 30) => true,");
        sb.AppendLine("            _ => false,");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    // Static string containing all read/write helper methods emitted into each record partial
    private const string HelperSource = @"
    // --- Generated Read Helpers ---
    private static ushort ReadU2(ref System.Buffers.SequenceReader<byte> r, Marklio.Stdf.Endianness e)
    {
        System.Span<byte> buf = stackalloc byte[2]; r.TryCopyTo(buf); r.Advance(2);
        return e == Marklio.Stdf.Endianness.LittleEndian ? System.Buffers.Binary.BinaryPrimitives.ReadUInt16LittleEndian(buf) : System.Buffers.Binary.BinaryPrimitives.ReadUInt16BigEndian(buf);
    }
    private static short ReadI2(ref System.Buffers.SequenceReader<byte> r, Marklio.Stdf.Endianness e)
    {
        System.Span<byte> buf = stackalloc byte[2]; r.TryCopyTo(buf); r.Advance(2);
        return e == Marklio.Stdf.Endianness.LittleEndian ? System.Buffers.Binary.BinaryPrimitives.ReadInt16LittleEndian(buf) : System.Buffers.Binary.BinaryPrimitives.ReadInt16BigEndian(buf);
    }
    private static uint ReadU4(ref System.Buffers.SequenceReader<byte> r, Marklio.Stdf.Endianness e)
    {
        System.Span<byte> buf = stackalloc byte[4]; r.TryCopyTo(buf); r.Advance(4);
        return e == Marklio.Stdf.Endianness.LittleEndian ? System.Buffers.Binary.BinaryPrimitives.ReadUInt32LittleEndian(buf) : System.Buffers.Binary.BinaryPrimitives.ReadUInt32BigEndian(buf);
    }
    private static int ReadI4(ref System.Buffers.SequenceReader<byte> r, Marklio.Stdf.Endianness e)
    {
        System.Span<byte> buf = stackalloc byte[4]; r.TryCopyTo(buf); r.Advance(4);
        return e == Marklio.Stdf.Endianness.LittleEndian ? System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian(buf) : System.Buffers.Binary.BinaryPrimitives.ReadInt32BigEndian(buf);
    }
    private static float ReadR4(ref System.Buffers.SequenceReader<byte> r, Marklio.Stdf.Endianness e)
    {
        System.Span<byte> buf = stackalloc byte[4]; r.TryCopyTo(buf); r.Advance(4);
        return e == Marklio.Stdf.Endianness.LittleEndian ? System.Buffers.Binary.BinaryPrimitives.ReadSingleLittleEndian(buf) : System.Buffers.Binary.BinaryPrimitives.ReadSingleBigEndian(buf);
    }
    private static double ReadR8(ref System.Buffers.SequenceReader<byte> r, Marklio.Stdf.Endianness e)
    {
        System.Span<byte> buf = stackalloc byte[8]; r.TryCopyTo(buf); r.Advance(8);
        return e == Marklio.Stdf.Endianness.LittleEndian ? System.Buffers.Binary.BinaryPrimitives.ReadDoubleLittleEndian(buf) : System.Buffers.Binary.BinaryPrimitives.ReadDoubleBigEndian(buf);
    }
    private static ulong ReadU8(ref System.Buffers.SequenceReader<byte> r, Marklio.Stdf.Endianness e)
    {
        System.Span<byte> buf = stackalloc byte[8]; r.TryCopyTo(buf); r.Advance(8);
        return e == Marklio.Stdf.Endianness.LittleEndian ? System.Buffers.Binary.BinaryPrimitives.ReadUInt64LittleEndian(buf) : System.Buffers.Binary.BinaryPrimitives.ReadUInt64BigEndian(buf);
    }
    private static long ReadI8(ref System.Buffers.SequenceReader<byte> r, Marklio.Stdf.Endianness e)
    {
        System.Span<byte> buf = stackalloc byte[8]; r.TryCopyTo(buf); r.Advance(8);
        return e == Marklio.Stdf.Endianness.LittleEndian ? System.Buffers.Binary.BinaryPrimitives.ReadInt64LittleEndian(buf) : System.Buffers.Binary.BinaryPrimitives.ReadInt64BigEndian(buf);
    }
    private static System.DateTime ReadDateTime(ref System.Buffers.SequenceReader<byte> r, Marklio.Stdf.Endianness e)
    {
        uint secs = ReadU4(ref r, e);
        return secs == 0 ? default : new System.DateTime(1970, 1, 1, 0, 0, 0, System.DateTimeKind.Utc).AddSeconds(secs);
    }
    private static string ReadCn(ref System.Buffers.SequenceReader<byte> r)
    {
        r.TryRead(out byte len);
        if (len == 0) return string.Empty;
        System.Span<byte> buf = stackalloc byte[len];
        r.TryCopyTo(buf); r.Advance(len);
        return System.Text.Encoding.ASCII.GetString(buf);
    }
    private static string ReadCf(ref System.Buffers.SequenceReader<byte> r, int length)
    {
        System.Span<byte> buf = length <= 512 ? stackalloc byte[length] : new byte[length];
        r.TryCopyTo(buf); r.Advance(length);
        return System.Text.Encoding.ASCII.GetString(buf).TrimEnd();
    }
    private static string ReadSn(ref System.Buffers.SequenceReader<byte> r, Marklio.Stdf.Endianness e)
    {
        ushort len = ReadU2(ref r, e);
        if (len == 0) return string.Empty;
        System.Span<byte> buf = len <= 512 ? stackalloc byte[len] : new byte[len];
        r.TryCopyTo(buf); r.Advance(len);
        return System.Text.Encoding.ASCII.GetString(buf);
    }
    private static byte[]? ReadBn(ref System.Buffers.SequenceReader<byte> r)
    {
        r.TryRead(out byte len);
        if (len == 0) return System.Array.Empty<byte>();
        var buf = new byte[len]; r.TryCopyTo(buf); r.Advance(len); return buf;
    }
    private static System.Collections.BitArray? ReadDn(ref System.Buffers.SequenceReader<byte> r, Marklio.Stdf.Endianness e)
    {
        ushort bitCount = ReadU2(ref r, e);
        if (bitCount == 0) return new System.Collections.BitArray(0);
        int byteCount = (bitCount + 7) / 8;
        var buf = new byte[byteCount]; r.TryCopyTo(buf); r.Advance(byteCount);
        return new System.Collections.BitArray(buf) { Length = bitCount };
    }
    private static byte[] ReadU1Array(ref System.Buffers.SequenceReader<byte> r, int count) { var a = new byte[count]; r.TryCopyTo(a); r.Advance(count); return a; }
    private static ushort[] ReadU2Array(ref System.Buffers.SequenceReader<byte> r, int count, Marklio.Stdf.Endianness e) { var a = new ushort[count]; for (int i = 0; i < count; i++) a[i] = ReadU2(ref r, e); return a; }
    private static uint[] ReadU4Array(ref System.Buffers.SequenceReader<byte> r, int count, Marklio.Stdf.Endianness e) { var a = new uint[count]; for (int i = 0; i < count; i++) a[i] = ReadU4(ref r, e); return a; }
    private static ulong[] ReadU8Array(ref System.Buffers.SequenceReader<byte> r, int count, Marklio.Stdf.Endianness e) { var a = new ulong[count]; for (int i = 0; i < count; i++) a[i] = ReadU8(ref r, e); return a; }
    private static sbyte[] ReadI1Array(ref System.Buffers.SequenceReader<byte> r, int count) { var a = new sbyte[count]; for (int i = 0; i < count; i++) { r.TryRead(out byte b); a[i] = (sbyte)b; } return a; }
    private static short[] ReadI2Array(ref System.Buffers.SequenceReader<byte> r, int count, Marklio.Stdf.Endianness e) { var a = new short[count]; for (int i = 0; i < count; i++) a[i] = ReadI2(ref r, e); return a; }
    private static int[] ReadI4Array(ref System.Buffers.SequenceReader<byte> r, int count, Marklio.Stdf.Endianness e) { var a = new int[count]; for (int i = 0; i < count; i++) a[i] = ReadI4(ref r, e); return a; }
    private static long[] ReadI8Array(ref System.Buffers.SequenceReader<byte> r, int count, Marklio.Stdf.Endianness e) { var a = new long[count]; for (int i = 0; i < count; i++) a[i] = ReadI8(ref r, e); return a; }
    private static float[] ReadR4Array(ref System.Buffers.SequenceReader<byte> r, int count, Marklio.Stdf.Endianness e) { var a = new float[count]; for (int i = 0; i < count; i++) a[i] = ReadR4(ref r, e); return a; }
    private static double[] ReadR8Array(ref System.Buffers.SequenceReader<byte> r, int count, Marklio.Stdf.Endianness e) { var a = new double[count]; for (int i = 0; i < count; i++) a[i] = ReadR8(ref r, e); return a; }
    private static string[] ReadCnArray(ref System.Buffers.SequenceReader<byte> r, int count) { var a = new string[count]; for (int i = 0; i < count; i++) a[i] = ReadCn(ref r); return a; }
    private static string[] ReadSnArray(ref System.Buffers.SequenceReader<byte> r, int count, Marklio.Stdf.Endianness e) { var a = new string[count]; for (int i = 0; i < count; i++) a[i] = ReadSn(ref r, e); return a; }
    private static byte[] ReadNibbleArray(ref System.Buffers.SequenceReader<byte> r, int count)
    {
        var a = new byte[count]; int bc = (count + 1) / 2;
        for (int i = 0; i < bc; i++) { r.TryRead(out byte b); int idx = i * 2; if (idx < count) a[idx] = (byte)(b & 0x0F); if (idx + 1 < count) a[idx + 1] = (byte)((b >> 4) & 0x0F); }
        return a;
    }

    // --- Generated Write Helpers ---
    private static void WriteU1(System.Buffers.IBufferWriter<byte> w, byte v) { var s = w.GetSpan(1); s[0] = v; w.Advance(1); }
    private static void WriteI1(System.Buffers.IBufferWriter<byte> w, sbyte v) { var s = w.GetSpan(1); s[0] = (byte)v; w.Advance(1); }
    private static void WriteU2(System.Buffers.IBufferWriter<byte> w, ushort v, Marklio.Stdf.Endianness e)
    {
        var s = w.GetSpan(2);
        if (e == Marklio.Stdf.Endianness.LittleEndian) System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(s, v);
        else System.Buffers.Binary.BinaryPrimitives.WriteUInt16BigEndian(s, v);
        w.Advance(2);
    }
    private static void WriteI2(System.Buffers.IBufferWriter<byte> w, short v, Marklio.Stdf.Endianness e)
    {
        var s = w.GetSpan(2);
        if (e == Marklio.Stdf.Endianness.LittleEndian) System.Buffers.Binary.BinaryPrimitives.WriteInt16LittleEndian(s, v);
        else System.Buffers.Binary.BinaryPrimitives.WriteInt16BigEndian(s, v);
        w.Advance(2);
    }
    private static void WriteU4(System.Buffers.IBufferWriter<byte> w, uint v, Marklio.Stdf.Endianness e)
    {
        var s = w.GetSpan(4);
        if (e == Marklio.Stdf.Endianness.LittleEndian) System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(s, v);
        else System.Buffers.Binary.BinaryPrimitives.WriteUInt32BigEndian(s, v);
        w.Advance(4);
    }
    private static void WriteI4(System.Buffers.IBufferWriter<byte> w, int v, Marklio.Stdf.Endianness e)
    {
        var s = w.GetSpan(4);
        if (e == Marklio.Stdf.Endianness.LittleEndian) System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(s, v);
        else System.Buffers.Binary.BinaryPrimitives.WriteInt32BigEndian(s, v);
        w.Advance(4);
    }
    private static void WriteR4(System.Buffers.IBufferWriter<byte> w, float v, Marklio.Stdf.Endianness e)
    {
        var s = w.GetSpan(4);
        if (e == Marklio.Stdf.Endianness.LittleEndian) System.Buffers.Binary.BinaryPrimitives.WriteSingleLittleEndian(s, v);
        else System.Buffers.Binary.BinaryPrimitives.WriteSingleBigEndian(s, v);
        w.Advance(4);
    }
    private static void WriteR8(System.Buffers.IBufferWriter<byte> w, double v, Marklio.Stdf.Endianness e)
    {
        var s = w.GetSpan(8);
        if (e == Marklio.Stdf.Endianness.LittleEndian) System.Buffers.Binary.BinaryPrimitives.WriteDoubleLittleEndian(s, v);
        else System.Buffers.Binary.BinaryPrimitives.WriteDoubleBigEndian(s, v);
        w.Advance(8);
    }
    private static void WriteU8(System.Buffers.IBufferWriter<byte> w, ulong v, Marklio.Stdf.Endianness e)
    {
        var s = w.GetSpan(8);
        if (e == Marklio.Stdf.Endianness.LittleEndian) System.Buffers.Binary.BinaryPrimitives.WriteUInt64LittleEndian(s, v);
        else System.Buffers.Binary.BinaryPrimitives.WriteUInt64BigEndian(s, v);
        w.Advance(8);
    }
    private static void WriteI8(System.Buffers.IBufferWriter<byte> w, long v, Marklio.Stdf.Endianness e)
    {
        var s = w.GetSpan(8);
        if (e == Marklio.Stdf.Endianness.LittleEndian) System.Buffers.Binary.BinaryPrimitives.WriteInt64LittleEndian(s, v);
        else System.Buffers.Binary.BinaryPrimitives.WriteInt64BigEndian(s, v);
        w.Advance(8);
    }
    private static void WriteC1(System.Buffers.IBufferWriter<byte> w, char v) { var s = w.GetSpan(1); s[0] = (byte)v; w.Advance(1); }
    private static void WriteCn(System.Buffers.IBufferWriter<byte> w, string? v)
    {
        if (v != null && v.Length > 255) throw new System.InvalidOperationException($""String length {v.Length} exceeds maximum Cn length of 255 characters."");
        byte len = (byte)(v?.Length ?? 0); var s = w.GetSpan(1 + len); s[0] = len;
        if (len > 0) System.Text.Encoding.ASCII.GetBytes(v!, s.Slice(1, len));
        w.Advance(1 + len);
    }
    private static void WriteSn(System.Buffers.IBufferWriter<byte> w, string? v, Marklio.Stdf.Endianness e)
    {
        ushort len = (ushort)(v?.Length ?? 0); var s = w.GetSpan(2 + len);
        if (e == Marklio.Stdf.Endianness.LittleEndian) System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(s, len);
        else System.Buffers.Binary.BinaryPrimitives.WriteUInt16BigEndian(s, len);
        if (len > 0) System.Text.Encoding.ASCII.GetBytes(v!, s.Slice(2, len));
        w.Advance(2 + len);
    }
    private static void WriteCf(System.Buffers.IBufferWriter<byte> w, string? v, int length)
    {
        var s = w.GetSpan(length); s.Slice(0, length).Fill((byte)' ');
        if (v != null) { int cl = System.Math.Min(v.Length, length); System.Text.Encoding.ASCII.GetBytes(v.AsSpan(0, cl), s); }
        w.Advance(length);
    }
    private static void WriteBn(System.Buffers.IBufferWriter<byte> w, byte[]? v)
    {
        if (v != null && v.Length > 255) throw new System.InvalidOperationException($""Byte array length {v.Length} exceeds maximum Bn length of 255 bytes."");
        byte len = (byte)(v?.Length ?? 0); var s = w.GetSpan(1 + len); s[0] = len;
        if (len > 0) v.AsSpan().CopyTo(s.Slice(1));
        w.Advance(1 + len);
    }
    private static void WriteDn(System.Buffers.IBufferWriter<byte> w, System.Collections.BitArray? v, Marklio.Stdf.Endianness e)
    {
        if (v != null && v.Length > ushort.MaxValue) throw new System.InvalidOperationException($""BitArray length {v.Length} exceeds maximum Dn bit count of {ushort.MaxValue}."");
        ushort bc = (ushort)(v?.Length ?? 0); int byc = (bc + 7) / 8;
        var s = w.GetSpan(2 + byc);
        if (e == Marklio.Stdf.Endianness.LittleEndian) System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(s, bc);
        else System.Buffers.Binary.BinaryPrimitives.WriteUInt16BigEndian(s, bc);
        if (byc > 0 && v != null) { var bytes = new byte[byc]; v.CopyTo(bytes, 0); bytes.AsSpan().CopyTo(s.Slice(2)); }
        w.Advance(2 + byc);
    }
    private static void WriteN1(System.Buffers.IBufferWriter<byte> w, byte v) { var s = w.GetSpan(1); s[0] = (byte)(v & 0x0F); w.Advance(1); }
    private static void WriteDateTime(System.Buffers.IBufferWriter<byte> w, System.DateTime v, Marklio.Stdf.Endianness e)
    {
        uint secs = Marklio.Stdf.Types.StdfDateTime.ToStdf(v);
        WriteU4(w, secs, e);
    }
    private static void WriteU1Array(System.Buffers.IBufferWriter<byte> w, byte[] a) { var s = w.GetSpan(a.Length); a.AsSpan().CopyTo(s); w.Advance(a.Length); }
    private static void WriteU2Array(System.Buffers.IBufferWriter<byte> w, ushort[] a, Marklio.Stdf.Endianness e) { foreach (var v in a) WriteU2(w, v, e); }
    private static void WriteU4Array(System.Buffers.IBufferWriter<byte> w, uint[] a, Marklio.Stdf.Endianness e) { foreach (var v in a) WriteU4(w, v, e); }
    private static void WriteU8Array(System.Buffers.IBufferWriter<byte> w, ulong[] a, Marklio.Stdf.Endianness e) { foreach (var v in a) WriteU8(w, v, e); }
    private static void WriteI1Array(System.Buffers.IBufferWriter<byte> w, sbyte[] a) { var s = w.GetSpan(a.Length); for (int i = 0; i < a.Length; i++) s[i] = (byte)a[i]; w.Advance(a.Length); }
    private static void WriteI2Array(System.Buffers.IBufferWriter<byte> w, short[] a, Marklio.Stdf.Endianness e) { foreach (var v in a) WriteI2(w, v, e); }
    private static void WriteI4Array(System.Buffers.IBufferWriter<byte> w, int[] a, Marklio.Stdf.Endianness e) { foreach (var v in a) WriteI4(w, v, e); }
    private static void WriteI8Array(System.Buffers.IBufferWriter<byte> w, long[] a, Marklio.Stdf.Endianness e) { foreach (var v in a) WriteI8(w, v, e); }
    private static void WriteR4Array(System.Buffers.IBufferWriter<byte> w, float[] a, Marklio.Stdf.Endianness e) { foreach (var v in a) WriteR4(w, v, e); }
    private static void WriteR8Array(System.Buffers.IBufferWriter<byte> w, double[] a, Marklio.Stdf.Endianness e) { foreach (var v in a) WriteR8(w, v, e); }
    private static void WriteCnArray(System.Buffers.IBufferWriter<byte> w, string[] a) { foreach (var v in a) WriteCn(w, v); }
    private static void WriteSnArray(System.Buffers.IBufferWriter<byte> w, string[] a, Marklio.Stdf.Endianness e) { foreach (var v in a) WriteSn(w, v, e); }
    private static void WriteNibbleArray(System.Buffers.IBufferWriter<byte> w, byte[] a)
    {
        int bc = (a.Length + 1) / 2; var s = w.GetSpan(bc); s.Slice(0, bc).Clear();
        for (int i = 0; i < a.Length; i++) { int bi = i / 2; if (i % 2 == 0) s[bi] = (byte)(a[i] & 0x0F); else s[bi] |= (byte)((a[i] & 0x0F) << 4); }
        w.Advance(bc);
    }
";

    private static ulong AllBitsMask(int bitCount)
    {
        if (bitCount >= 64) return ulong.MaxValue;
        if (bitCount <= 0) return 0;
        return (1UL << bitCount) - 1;
    }

    private static bool IsValueTypeStdfField(StdfFieldType t) => t switch
    {
        StdfFieldType.U1 or StdfFieldType.I1 or StdfFieldType.U2 or StdfFieldType.I2 or
        StdfFieldType.U4 or StdfFieldType.I4 or StdfFieldType.U8 or StdfFieldType.I8 or
        StdfFieldType.R4 or StdfFieldType.R8 or
        StdfFieldType.B1 or StdfFieldType.C1 or StdfFieldType.N1 or StdfFieldType.DateTime => true,
        _ => false,
    };
}
