namespace Marklio.Stdf;

/// <summary>
/// Controls which levels of summary records are generated by summary extension methods.
/// </summary>
[Flags]
public enum SummaryScope
{
    /// <summary>Generate summaries per (head, site) pair.</summary>
    HeadSite = 1,

    /// <summary>Generate summaries per head (SiteNumber = 255 means all sites).</summary>
    Head = 2,

    /// <summary>Generate overall summaries (HeadNumber = 255, SiteNumber = 255).</summary>
    Overall = 4,

    /// <summary>Generate all summary levels.</summary>
    All = HeadSite | Head | Overall,
}
